#!/usr/bin/env bash

debug_port=${DEBUG_PORT:-1099}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Start the TCP tunnel
ngrok_cmd="bin/ngrok tcp -authtoken ${NGROK_API_TOKEN} -log stdout --log-level debug ${NGROK_OPTS} ${debug_port}"
echo "Starting ngrok..."
eval "$ngrok_cmd &"
ngrok_pid=$!

export JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} -Xverify:none -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$debug_port -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

eval "$@"
